<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SlmException\Module'                                  => __DIR__ . '/Module.php',
    'SlmException\Exception\ExceptionInterface'            => __DIR__ . '/src/SlmException/Exception/ExceptionInterface.php',
    'SlmException\Exception\PageNotFoundInterface'         => __DIR__ . '/src/SlmException/Exception/PageNotFoundInterface.php',
    'SlmException\Exception\ForbiddenInterface'            => __DIR__ . '/src/SlmException/Exception/ForbiddenInterface.php',
    'SlmException\Exception\ServerErrorInterface'          => __DIR__ . '/src/SlmException/Exception/ServerErrorInterface.php',
    'SlmException\Exception\BadRequestInterface'           => __DIR__ . '/src/SlmException/Exception/BadRequestInterface.php',
    'SlmException\Exception\MethodNotAllowedInterface'     => __DIR__ . '/src/SlmException/Exception/MethodNotAllowedInterface.php',
    'SlmException\Exception\UnauthorizedInterface'         => __DIR__ . '/src/SlmException/Exception/UnauthorizedInterface.php',
    'SlmException\Mvc\View\Http\ExceptionStrategy'         => __DIR__ . '/src/SlmException/Mvc/View/Http/ExceptionStrategy.php',
    'SlmExceptionTest\Mvc\View\Http\ExceptionStrategyTest' => __DIR__ . '/tests/SlmExceptionTest/Mvc/View/ExceptionStrategyTest.php',
);